const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES: 'categories/SET_CATEGORIES',
    FETCH_CATEGORIES_INIT: 'categories/FETCH_CATEGORIES_INIT',
    FETCH_CATEGORIES_SUCCESS: 'categories/FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILED: 'categories/FETCH_CATEGORIES_FAILED',

}

export default CATEGORIES_ACTION_TYPES;